NAME=LLAMA_8B_4K_pp_run8_plan
NNODES=1
NPROC_PER_NODE=8
PLAN_NGPUS=8
RUNTIME_NGPUS=8
DATASIZE=4K
MODEL_ID=/nfs/andy/models/Llama3.1-8B
DATASET_PATH=/nfs/andy/datasets/bookcorpus_llama3_4K
CODE=/nfs/andy/code/nnscaler-M/examples/llama/train.py
PIPLINE=True
